// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodNewsGrid.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoodNewsGrid.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810144443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoodNewsGrid.Core.Models.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("MoodNewsGrid.Core.Models.NewsRewrite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactsCheckIssues")
                        .HasColumnType("text");

                    b.Property<bool>("FactsCheckPassed")
                        .HasColumnType("boolean");

                    b.Property<int>("Mood")
                        .HasColumnType("integer");

                    b.Property<Guid>("NewsItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("RewrittenText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NewsItemId", "Mood")
                        .IsUnique();

                    b.ToTable("NewsRewrites");
                });

            modelBuilder.Entity("MoodNewsGrid.Core.Models.NewsRewrite", b =>
                {
                    b.HasOne("MoodNewsGrid.Core.Models.NewsItem", "NewsItem")
                        .WithMany("Rewrites")
                        .HasForeignKey("NewsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");
                });

            modelBuilder.Entity("MoodNewsGrid.Core.Models.NewsItem", b =>
                {
                    b.Navigation("Rewrites");
                });
#pragma warning restore 612, 618
        }
    }
}
